version: '3'

services:
  mysql:
    image: mysql:8.0.22
    tmpfs: /var/lib/mysql:rw
    command:
      --default-time-zone=+8:00
      --innodb-buffer-pool-size=20M
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_DATABASE=spring_base"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"